CREATE TABLE public.users (
      id bigint NOT NULL,
      created_at timestamp(6) with time zone NOT NULL,
      password character varying(255) NOT NULL,
      role character varying(255),
      updated_at timestamp(6) with time zone NOT NULL,
      username character varying(255) NOT NULL,
      CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_username UNIQUE (username);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
