server:
  port: 8999

spring:
  application:
    name: saga-orchestrator
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

customer:
  service: ${CUSTOMER_SERVICE_URL}
event:
  service: ${EVENT_SERVICE_URL}