server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

app:
  services:
    customer:
      url: ${CUSTOMER_SERVICE_URL}
    security:
      url: ${SECURITY_SERVICE_URL}
    event:
      url: ${EVENT_SERVICE_URL}
    saga:
      url: ${SAGA_ORCHESTRATOR_URL}

spring:
  application:
    name: api-gateway

  cloud:
    gateway.server.webflux:
      routes:
        - id: security-service
          uri: ${SECURITY_SERVICE_URL}
          predicates:
            - Path=/auth/**
# http://localhost:8082
        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL}
          predicates:
            - Path=/customers/**
# http://localhost:8083
        - id: event-service
          uri: ${EVENT_SERVICE_URL}
          predicates:
            - Path=/events/**
# http://localhost:8085
        - id: saga-orchestrator
          uri: ${SAGA_ORCHESTRATOR_URL}
          predicates:
            - Path=/registrations/**
# http://localhost:8086

jwt:
  public-key: ${JWT_PUBLIC_KEY}

visual:
  enigma: ${VISUAL_ENGIMA_URL}