server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway.server.webflux:
      routes:
        - id: security-service
          uri: ${SECURITY_SERVICE_URL}
          predicates:
            - Path=/auth/**
# http://localhost:8082
        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL}
          predicates:
            - Path=/customers/**
# http://localhost:8083
jwt:
  public-key: ${JWT_PUBLIC_KEY}

visual:
  enigma: ${VISUAL_ENGIMA_URL}