CREATE TABLE public.saga_instances (
   id bigint NOT NULL,
   business_id character varying(255),
   context jsonb,
   correlation_id character varying(255),
   created_at timestamp(6) with time zone NOT NULL,
   current_step character varying(255),
   saga_type character varying(255),
   status character varying(255),
   updated_at timestamp(6) with time zone NOT NULL,
   CONSTRAINT saga_instances_current_step_check CHECK ( current_step IN ('REGISTRATION_STARTED', 'CUSTOMER_VALIDATION', 'CUSTOMER_VALIDATED', 'CUSTOMER_VALIDATION_FAILED', 'SEAT_RESERVATION', 'SEAT_RESERVED', 'SEAT_RESERVATION_FAILED', 'SEAT_RELEASING', 'PAYMENT_REQUIRED', 'PAYMENT_VERIFICATION_STARTED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'REGISTRATION_COMPLETED', 'REGISTRATION_COMPENSATED')),
   CONSTRAINT saga_instances_saga_type_check CHECK (saga_type = 'REGISTRATION'),
   CONSTRAINT saga_instances_status_check CHECK (status IN ('STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'COMPENSATING', 'COMPENSATED'))
);


ALTER TABLE public.saga_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saga_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.saga_instances
    ADD CONSTRAINT saga_instances_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.saga_instances
    ADD CONSTRAINT uk_correlation_id UNIQUE (correlation_id);
