--
-- PostgreSQL database dump
--

\restrict WJntt7FXg8eH1h0bCZqGOQ4w4deVtRbvtTInlraLfcWZSxdm1cn7lqtOFQ7cxIB

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: outbox_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_messages (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    exchange character varying(200) NOT NULL,
    message_type character varying(100) NOT NULL,
    next_retry_at timestamp(6) with time zone,
    outbox_message_id uuid NOT NULL,
    payload text NOT NULL,
    published_at timestamp(6) with time zone,
    retry_count integer NOT NULL,
    routing_key character varying(200) NOT NULL,
    status character varying(20) NOT NULL,
    failure_type character varying(50),
    failure_reason text,
    failed_at timestamp with time zone,
    CONSTRAINT outbox_messages_message_type_check CHECK (((message_type)::text = 'PAYMENT_VERIFY_RESPONSE'::text)),
    CONSTRAINT outbox_messages_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: outbox_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.outbox_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    currency character varying(3) NOT NULL,
    customer_id bigint,
    paid_at timestamp(6) with time zone,
    razorpay_order_id character varying(255) NOT NULL,
    razorpay_payment_id character varying(255),
    registration_id character varying(255) NOT NULL,
    status character varying(30) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: processed_webhook_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processed_webhook_events (
    id bigint NOT NULL,
    processed_at timestamp(6) with time zone NOT NULL,
    razorpay_event_id character varying(255) NOT NULL
);


--
-- Name: processed_webhook_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.processed_webhook_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processed_webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: outbox_messages outbox_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT outbox_messages_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: processed_webhook_events processed_webhook_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_webhook_events
    ADD CONSTRAINT processed_webhook_events_pkey PRIMARY KEY (id);


--
-- Name: payments uk6ata50j64oxc4pim0kar557fn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk6ata50j64oxc4pim0kar557fn UNIQUE (registration_id);


--
-- Name: processed_webhook_events uk_webhook_event_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processed_webhook_events
    ADD CONSTRAINT uk_webhook_event_id UNIQUE (razorpay_event_id);


--
-- Name: payments ukc3w49re3w3eiexjdnm9khcsd8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukc3w49re3w3eiexjdnm9khcsd8 UNIQUE (razorpay_order_id);


--
-- Name: outbox_messages ukrhhijauhysh526e0ea9s8opk0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT ukrhhijauhysh526e0ea9s8opk0 UNIQUE (outbox_message_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_outbox_status_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_outbox_status_created_at ON public.outbox_messages USING btree (status, created_at);


--
-- PostgreSQL database dump complete
--

\unrestrict WJntt7FXg8eH1h0bCZqGOQ4w4deVtRbvtTInlraLfcWZSxdm1cn7lqtOFQ7cxIB

