CREATE TABLE public.events (
       id bigint NOT NULL,
       available_seats integer NOT NULL,
       created_at timestamp(6) with time zone NOT NULL,
       currency character varying(4) NOT NULL,
       description character varying(255),
       event_date timestamp(6) without time zone,
       name character varying(255),
       price numeric(19,2) NOT NULL,
       updated_at timestamp(6) with time zone NOT NULL,
       CONSTRAINT events_currency_check CHECK (currency = 'INR')
);

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.seat_releases (
      id bigint NOT NULL,
      event_id bigint NOT NULL,
      registration_id character varying(255) NOT NULL
);

ALTER TABLE public.seat_releases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seat_releases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.seat_reservations (
      id bigint NOT NULL,
      event_id bigint NOT NULL,
      registration_id character varying(255) NOT NULL
);

ALTER TABLE public.seat_reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seat_reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.seat_releases
    ADD CONSTRAINT seat_releases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.seat_reservations
    ADD CONSTRAINT seat_reservations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.seat_reservations
    ADD CONSTRAINT uk_registration_event UNIQUE (registration_id, event_id);

ALTER TABLE ONLY public.seat_releases
    ADD CONSTRAINT uk_release_registration_event UNIQUE (registration_id, event_id);