CREATE TABLE public.outbox_messages (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    destination_type character varying(10) NOT NULL,
    destination_name character varying(200) NOT NULL,
    message_type character varying(100) NOT NULL,
    next_retry_at timestamp(6) with time zone,
    outbox_message_id uuid NOT NULL,
    payload text NOT NULL,
    published_at timestamp(6) with time zone,
    retry_count integer NOT NULL,
    routing_key character varying(200),
    status character varying(20) NOT NULL,
    failure_type VARCHAR(50),
    failure_reason TEXT,
    failed_at TIMESTAMPTZ
    CONSTRAINT outbox_messages_destination_type_check
        CHECK (destination_type IN ('RABBITMQ', 'KAFKA')),
    CONSTRAINT outbox_messages_message_type_check
        CHECK (message_type IN ('CUSTOMER_VALIDATION_REQUEST', 'SEAT_RESERVATION_REQUEST',
                                'SEAT_UNRESERVE_REQUEST','PAYMENT_ORDER_REQUEST',
                                'REGISTRATION_COMPLETED', 'REGISTRATION_FAILED')),
    CONSTRAINT outbox_messages_status_check
        CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

ALTER TABLE public.outbox_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT outbox_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT uk_outbox_message_id UNIQUE (outbox_message_id);

CREATE INDEX idx_outbox_status_created_at ON public.outbox_messages
    USING btree (status, created_at);