package com.laughingenigma.saga_orchestrator.entity;

public enum SagaStep {
    //REGISTRATION
    REGISTRATION_STARTED,

    CUSTOMER_VALIDATION,
    CUSTOMER_VALIDATED,
    CUSTOMER_VALIDATION_FAILED,

    SEAT_RESERVATION,
    SEAT_RESERVED,
    SEAT_RESERVATION_FAILED,
    SEAT_RELEASING,
    SEAT_UNRESERVED,

    PAYMENT_REQUIRED,
    PAYMENT_VERIFICATION_STARTED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,

    REGISTRATION_COMPLETED

    // ...
}
