CREATE TABLE public.customers (
      id bigint NOT NULL,
      created_at timestamp(6) with time zone NOT NULL,
      email character varying(255),
      first_name character varying(255),
      last_name character varying(255),
      status character varying(255),
      updated_at timestamp(6) with time zone NOT NULL,
      username character varying(255),
      CONSTRAINT customers_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT uk_username UNIQUE (username);
