CREATE TABLE public.outbox_messages (
                                        id bigint NOT NULL,
                                        created_at timestamp(6) with time zone NOT NULL,
                                        exchange character varying(200) NOT NULL,
                                        message_type character varying(100) NOT NULL,
                                        next_retry_at timestamp(6) with time zone,
                                        outbox_message_id uuid NOT NULL,
                                        payload text NOT NULL,
                                        published_at timestamp(6) with time zone,
                                        retry_count integer NOT NULL,
                                        routing_key character varying(200) NOT NULL,
                                        status character varying(20) NOT NULL,
                                        CONSTRAINT outbox_messages_message_type_check CHECK (message_type = 'PAYMENT_VERIFY_RESPONSE'),
                                        CONSTRAINT outbox_messages_status_check CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

ALTER TABLE public.outbox_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payments (
                                 id bigint NOT NULL,
                                 amount numeric(12,2) NOT NULL,
                                 created_at timestamp(6) with time zone NOT NULL,
                                 currency character varying(3) NOT NULL,
                                 customer_id bigint,
                                 paid_at timestamp(6) with time zone,
                                 razorpay_order_id character varying(255) NOT NULL,
                                 razorpay_payment_id character varying(255),
                                 registration_id character varying(255) NOT NULL,
                                 status character varying(30) NOT NULL,
                                 updated_at timestamp(6) with time zone NOT NULL,
                                 CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.processed_webhook_events (
                                                 id bigint NOT NULL,
                                                 processed_at timestamp(6) with time zone NOT NULL,
                                                 razorpay_event_id character varying(255) NOT NULL
);

ALTER TABLE public.processed_webhook_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processed_webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT outbox_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.processed_webhook_events
    ADD CONSTRAINT processed_webhook_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk_registration_id UNIQUE (registration_id);

ALTER TABLE ONLY public.processed_webhook_events
    ADD CONSTRAINT uk_webhook_event_id UNIQUE (razorpay_event_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk_razorpay_order_id UNIQUE (razorpay_order_id);

ALTER TABLE ONLY public.outbox_messages
    ADD CONSTRAINT uk_outbox_message_id UNIQUE (outbox_message_id);

CREATE INDEX idx_outbox_status_created_at ON public.outbox_messages USING btree (status, created_at);